betagram/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import UserLogoutView, UserLoginView, UserRegisterView, ProfileView, EditProfileView, RequestView, FollowerListView, FollowingListView
from django.conf.urls.static import static
from . import settings
from posts.views import PostCreateView
from users.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', UserLoginView.as_view(), name = 'login'),
    path('logout/', UserLogoutView.as_view(), name = 'logout'),
    path('register/', UserRegisterView, name = 'register'),
    path('', include('feed.urls')),
    path('<int:pk>/', include('posts.urls')),
    path('search/', include('search.urls')),
    path('notifications/', include('notifications.urls')),
    path('profile-<username>/', ProfileView, name = 'profile'),
    path('profile-<username>/followers/', FollowerListView, name = 'follower_list'),
    path('profile-<username>/following/', FollowingListView, name = 'following_list'),
    path('profile-<username>/edit/', EditProfileView, name = 'profile-edit'),
    path('create/', PostCreateView.as_view(), name = 'create'),
    path('requests/', RequestView, name = 'requests'),
    path('password-reset/', PasswordResetView.as_view(), name = 'password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name = 'password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path, include
from .views import FeedView

app_name = 'feed'

urlpatterns = [
    path('', FeedView, name = 'home'),
]

notifications/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import NotifView
app_name = 'notifs'

urlpatterns = [
    path('', NotifView, name = 'notification_page')
]

search/urls.py
from django.urls import path, include
from .views import SearchResultView
app_name = 'search'

urlpatterns = [
    path('', SearchResultView.as_view(), name = 'search_result'),
]

betagram/templates/betagram/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title%}{% endblock %}</title>

    {% load static %}

    <style type="text/css">
      body {
        margin: 0 auto;
      }
      .infinite-item, .loading {
        margin-bottom: 5px;
        padding: 25px 0;
      }
      .loading {
        background-color: #333;
        color: aliceblue;
      }
      a.infinite-more-link{
        color: aliceblue;
      }
    </style>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"></script>
    <script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>
  </head>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'feed:home' %}">Home</a>

      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#topNavBar"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="topNavbar">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">

          <li class="nav-item ">
            <a class="nav-link" href="{% url 'notifs:notification_page' %}"
              >Notifications {% block has_notif %}{% endblock %}<span class="sr-only">(current)</span></a
            >
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'create' %}"
              >Create New Post<span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
        {% endif %} {% if request.user.is_authenticated %}

        <ul class="navbar-nav ml-auto">
          <form
            class="form-inline my-2 my-lg-0"
            method="GET"
            action="{% url 'search:search_result' %}"
          >
            <input
              name="q"
              class="form-control mr-sm-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
              Search
            </button>
          </form>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' request.user.username %}"
              >Profile<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"
              >Logout<span class="sr-only">(current)</span></a
            >
          </li>
        </ul>

        {% else %}

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}"
              >Login <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}"
              >Register<span class="sr-only">(current)</span></a
            >
          </li>
        </ul>

        {% endif %}
      </div>
    </div>
  </nav>

  <body>
    <div class="container">
      <br />
      <br />
      <br />
      <br />

      {% block body %}{% endblock %}
    </div>


<script>
  var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function () {
      $('.loading').show();
    },
    onAfterPageLoad: function ($items) {
      $('.loading').hide();
    }
  });
</script>
  </body>
</html>

betagram/templates/betagram/index.html
{% extends 'betagram/base.html' %}

{% block body %}

{% if request.user.is_authenticated %}
<h1>Feed</h1>

<div class="infinite-container">
    {% for post in posts %}
      <div class="infinite-item">
        <a href = "{% url 'profile' post.owner.username %}">
            <img src="{{post.owner.profile.image.url}}" class = "rounded-circle" width="50px" height="50px">
            <h3>{{post.owner.username}}</h3>
        </a>
        <a href = "{{ post.get_absolute_url }}"><img src="{{post.image.url}}"></a>
        <h2>{{post.likecount}}</h2>
        <h3>{{post.caption}}</h3>
      </div>
    {% endfor %}
</div>


  {% if posts.has_next %}
  <div class="loading">
    <h4><a class="infinite-more-link" href="?page={{posts.next_page_number}}">More</a></h4>
  </div>
  {% endif %}


{% else %}
<h1>Betagram</h1>

{% endif %}

{% endblock %}