betagram/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import UserLogoutView, UserLoginView, UserRegisterView, ProfileView, EditProfileView, RequestView, FollowerListView, FollowingListView
from django.conf.urls.static import static
from . import settings
from posts.views import PostCreateView
from users.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', UserLoginView.as_view(), name = 'login'),
    path('logout/', UserLogoutView.as_view(), name = 'logout'),
    path('register/', UserRegisterView, name = 'register'),
    path('', include('feed.urls')),
    path('<int:pk>/', include('posts.urls')),
    path('search/', include('search.urls')),
    path('notifications/', include('notifications.urls')),
    path('profile-<username>/', ProfileView, name = 'profile'),
    path('profile-<username>/followers/', FollowerListView, name = 'follower_list'),
    path('profile-<username>/following/', FollowingListView, name = 'following_list'),
    path('profile-<username>/edit/', EditProfileView, name = 'profile-edit'),
    path('create/', PostCreateView.as_view(), name = 'create'),
    path('requests/', RequestView, name = 'requests'),
    path('password-reset/', PasswordResetView.as_view(), name = 'password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name = 'password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path, include
from .views import FeedView

app_name = 'feed'

urlpatterns = [
    path('', FeedView, name = 'home'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import PostDetailView, PostUpdateView, PostDeleteView
app_name = 'posts'

urlpatterns = [
    path('', PostDetailView, name ='post_detail'),
    path('update/', PostUpdateView.as_view(), name = 'post_update'),
    path('delete/', PostDeleteView.as_view(), name= 'post_delete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from PIL import Image
from django.shortcuts import reverse


class Post(models.Model):
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    image = models.ImageField(upload_to='user_posts')
    caption = models.TextField(max_length=1000, blank=True)
    date = models.DateTimeField(default = now)
    likecount = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.owner.username} - {self.date}'

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk' : self.pk})

   # def save(self, *args, **kwargs):
    #    super().save(*args, **kwargs)

     #   img = Image.open(self.image.path)

      #  if img.height > 800 or img.width > 800:
       #     output_size = (800,800)
        #    img.thumbnail(output_size)
         #   img.save(self.image.path)


class LikeonPost(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    date = models.DateTimeField(default = now)

    class Meta:
        unique_together = ('user', 'post',)

    def __str__(self):
        return f'{self.user} liked {self.post.owner} post'
    
    def save(self, *args, **kwargs):
       self.post.likecount += 1
       self.post.save()
       super().save(*args, **kwargs)



class CommentonPost(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    comment = models.TextField(max_length=200)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    date = models.DateTimeField(default = now)
    likecount = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user} commented on {self.post.owner} post'

    

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .models import LikeonPost, CommentonPost
from notifications.models import Notification
# Create your views here.


@login_required
def PostDetailView(request, *args, **kwargs):

    post = get_object_or_404(Post, pk = kwargs['pk'])
    follower_find = post.owner.profile.followers.all().filter(user = request.user)
    
    if not request.user == post.owner and not follower_find.exists() :
        return HttpResponseForbidden()

    has_liked = LikeonPost.objects.filter(user = request.user, post = post).exists()
    
    if request.method == 'POST':
        
        if 'like' in request.POST:
            
            if has_liked:
                obj = LikeonPost.objects.filter(user = request.user, post = post).delete()
                post.likecount = post.likecount - 1
                Notification.objects.filter(concerned_user = post.owner, action_user = request.user, notification_type = 'like', post = post).delete()
                post.save()
                has_liked = False

            else:
                obj = LikeonPost.objects.create(user = request.user, post = post)
                Notification.objects.create(concerned_user = post.owner, action_user = request.user, notification_type = 'like', post = post)
                has_liked = True
            
        if 'comment' in request.POST:
            obj = CommentonPost.objects.create(user = request.user, post = post, comment = request.POST['comment'])
            Notification.objects.create(concerned_user = post.owner, action_user = request.user, notification_type = 'comment', post = post)


    return render(request, 'posts/detail.html', {'post' : post, 'has_liked': has_liked})



class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['image', 'caption']
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user     
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['image', 'caption']
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        
        form.instance.owner = self.request.user     
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    context_object_name = 'post'
    template_name = 'posts/post_delete_confirm.html'
    success_url = '/'

    def  test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Betagram {% endblock %}
{% block load_css %}
<link rel="stylesheet" href="{% static 'feed/style.css' %}">
{% endblock %}

<<<<<<< HEAD
=======

>>>>>>> 9f77611f867eb671b25c23ee9558862b004c60f9
{% block body %}
    <div class="row">
      <div class="infinite-item mx-auto col-lg-12 col-xs-12" style="object-fit: contain; border: 1px solid aquamarine; background-color: white;">
        
          <div class="row mx-auto" style="max-width: 800px; height: 60px;">
            
            <img src="{{post.owner.profile.image.url}}" class = "rounded-circle mx-3" width="50px" height="50px">
            <a href = "{% url 'profile' post.owner.username %}">  
                <h3 style="float:inline-start;" class="pt-1">{{post.owner.username}}</h3>
            </a>
            
            {% if post.owner == request.user %}
            <div class="btn-group ml-auto">
                <button class="btn btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-cog"></i>
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'posts:post_update' post.id %}">Update</a>
                    <a class="dropdown-item btn btn-danger btn-sm mt-1 mb-1" href="{% url 'posts:post_delete' post.id %}">Delete</a>
                </div>
            </div>
            {% endif %}
          </div>
          
        <div class="image mx-auto">
            <img src="{{post.image.url}}" class="post">
        </div>


        <div class="row mx-auto my-2" style="max-width: 800px; ">
            <form  class = "mr-3" method="POST" name = "like">
                {% csrf_token %}
        
                {% if has_liked %}
                <button class="btn btn-danger btn-md mt-1 mb-1" type="submit" name="like"><i class="fas fa-heart"></i></button>
                {% else %}
                    <button class="btn btn-outline-secondary btn-md mt-1 mb-1" type="submit" name="like"><i class="far fa-heart"></i></button>
                {% endif %}
        
            </form>

          <h2 style="color: black;">{{post.likecount}} likes</h2>
        </div>
    
        <div class="row mx-auto" style="max-width: 800px;">
          <h2 style="color: black; font-size: 25px;">{{post.caption}}</h2>
        </div>

      </div>
    </div>

    
    
    <h3>Comments</h3>
    <form class="mb-3" method="POST" name = "comment">
        {% csrf_token %}
        <input class="form-control" type="text" placeholder="Your comment here" name="comment">
        <button class="btn btn-outline-success btn-md mt-1 mb-1" type="submit">
         <i class="far fa-paper-plane"></i>
        </button> 
    </form>   

    

    {% if post.commentonpost_set.all%}
    
    {% for comment in post.commentonpost_set.all %}
        <div class="row" style="max-width: 800px; height: 70px;">
            <img src="{{comment.user.profile.image.url}}" class = "rounded-circle mx-3" width="40px" height="40px">
            <h4 class="pt-1">{{comment.user.username}} - {{comment.comment}}</h4>
          </div>
    {% endfor %}
    
    {% endif %}

{% endblock %}

posts/templates/posts/post_delete_confirm.html
{% extends 'base.html' %}


{% block title %}Delete Post{% endblock %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h4>Are you sure you want to delete this Post ? You will not be able to undo your actions.</h4>
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Yes</button>
        <a href = "{% url 'posts:post_detail' post.id %}" class="btn btn-outline-secondary">Cancel</a>
    </div>
</form>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}Edit Post{% endblock %}

{% block body %}

<div class="row mt-3">
    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 px-5 login_box mx-auto py-5" style="background-color: white; border: 1px solid gray;">
        <h4 class="subheading my-5" style="font-size: 32px; text-align: center; font-family: 'Source Sans Pro', sans-serif;;">Create New Post</h4>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
                <div class="form-group" style="text-align: center;">
                    <button class = "btn btn-outline-secondary btn-lg my-3 mx-auto" type="submit">Submit</button>
                </div>
    </form>
    </div>

</div>
{% endblock %}