betagram/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import UserLogoutView, UserLoginView, UserRegisterView, ProfileView, EditProfileView, RequestView, FollowerListView, FollowingListView
from django.conf.urls.static import static
from . import settings
from posts.views import PostCreateView
from users.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', UserLoginView.as_view(), name = 'login'),
    path('logout/', UserLogoutView.as_view(), name = 'logout'),
    path('register/', UserRegisterView, name = 'register'),
    path('', include('feed.urls')),
    path('<int:pk>/', include('posts.urls')),
    path('search/', include('search.urls')),
    path('notifications/', include('notifications.urls')),
    path('profile-<username>/', ProfileView, name = 'profile'),
    path('profile-<username>/followers/', FollowerListView, name = 'follower_list'),
    path('profile-<username>/following/', FollowingListView, name = 'following_list'),
    path('profile-<username>/edit/', EditProfileView, name = 'profile-edit'),
    path('create/', PostCreateView.as_view(), name = 'create'),
    path('requests/', RequestView, name = 'requests'),
    path('password-reset/', PasswordResetView.as_view(), name = 'password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name = 'password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path, include
from .views import FeedView

app_name = 'feed'

urlpatterns = [
    path('', FeedView, name = 'home'),
]

notifications/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import NotifView
app_name = 'notifs'

urlpatterns = [
    path('', NotifView, name = 'notification_page')
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import PostDetailView, PostUpdateView, PostDeleteView
app_name = 'posts'

urlpatterns = [
    path('', PostDetailView, name ='post_detail'),
    path('update/', PostUpdateView.as_view(), name = 'post_update'),
    path('delete/', PostDeleteView.as_view(), name= 'post_delete'),
]

notifications/models.py
from django.db import models
from users.models import Profile
from django.contrib.auth.models import User
from django.utils.timezone import now
from posts.models import Post
# Create your models here.


class Notification(models.Model):
    date = models.DateTimeField(default = now)
    concerned_user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='notification')
    action_user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='action_user')
    notification_type = models.CharField(max_length=10)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='history', blank = True, null = True)

    def __str__(self):
        return f'{self.action_user} {self.notification_type} {self.concerned_user}'
    

notifications/views.py
from django.shortcuts import render
from posts.models import LikeonPost, CommentonPost
from users.models import Request
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .models import Notification
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required
def NotifView(request):

    new_notifs = Notification.objects.filter(concerned_user = request.user, date__gt = request.user.time_track.last_login).order_by('-date')
    all_notifs = Notification.objects.filter(concerned_user = request.user, date__lt = request.user.time_track.last_login).order_by('-date')
    
    
    page = request.GET.get('page', 1)
    paginator = Paginator(all_notifs, 5)    
    
    try:
        old_notifs = paginator.page(page)
    except PageNotAnInteger:
        old_notifs = paginator.page(1)
    except EmptyPage:
        old_notifs = paginator.page(paginator.num_pages)

    request.user.time_track.save()
    return render(request, 'notifications/notifs.html', {'new_notifs': new_notifs, 'old_notifs' : old_notifs})

notifications/templates/notifications/notifs.html
{% extends 'base.html' %}


{% block title %}Notifications{% endblock %}

{% block body %}


<br>
<a href="{% url 'requests' %}">
    <div class="row" style="max-width: 800px; height: 30px;">
        <img src="/media/default.jpg" class = "rounded-circle mx-4" width="50px" height="50px">
        <h2 class="pt-1">Follow Requests</h2>   
    </div>
    <br>
</a>
<hr>
<br>


<h2>Notifications</h2>
<br>

{% if not new_notifs %}
    <h5>No new notifications</h5>
    <br>
{% endif %}

{% for notification in new_notifs %}


    {% if notification.notification_type == 'request' or notification.notification_type == 'req_accept' %}

        <a href = "{% url 'profile' notification.action_user.username %}">
            <div class="row" style="max-width: 800px; height: 60px;">
                <img src="{{notification.action_user.profile.image.url}}" class = "rounded-circle mx-4" width="50px" height="50px">

                {% if notification.notification_type == 'request' %}
                <h3 class="pt-1">{{notification.action_user.username}} wants to follow you </h3>
    
                {% else %}
                <h3 class="pt-1">{{notification.action_user.username}} accepted your follow request </h3>
    
                {% endif %}
            </div>
        </a>



    {% elif notification.notification_type == 'like' and not notification.action_user == request.user %}

    <a href = "{% url 'posts:post_detail' notification.post.id %}">
      <div class="row" style="max-width: 800px; height: 30px;">
        <img src="{{notification.post.image.url}}" class="mx-4" width="50px" height="50px">
        <h3 class="pt-1">{{notification.action_user.username}} liked your post </h3>
      </div>
    </a>


    {% else %}
    
        {% if not notification.action_user == request.user %}


        <a href = "{% url 'posts:post_detail' notification.post.id %}">
        <div class="row" style="max-width: 800px; height: 30px;">
                <img src="{{notification.post.image.url}}" class="mx-4" width="50px" height="50px">
                <h3 class="pt-1">{{notification.action_user.username}} commented on your post </h3>
        
        </div>
        </a>
        
        {% endif %}

    {% endif %}

<br>

{% endfor %}




<hr>


<h3 class="pt-3">Earlier</h3>

<br>

<div class="infinite-container">

    {% for notification in old_notifs %}

      {% if notification.notification_type == 'request' or notification.notification_type == 'req_accept' %}
      
      <div class="infinite-item">
        <a href = "{% url 'profile' notification.action_user.username %}">

            <div class="row" style="max-width: 800px; height: 30px;">
                <img src="{{notification.action_user.profile.image.url}}" class = "rounded-circle mx-4" width="50px" height="50px">

                {% if notification.notification_type == 'request' %}
                <h3 class="pt-1">{{notification.action_user.username}} wants to follow you </h3>

                {% else %}
                <h3 class="pt-1">{{notification.action_user.username}} accepted your follow request </h3>

                {% endif %}  
            </div>
        </a>
      </div>


      {% elif notification.notification_type == 'like' %}
      
      <div class="infinite-item">
        <a href = "{% url 'posts:post_detail' notification.post.id %}">
            <div class="row" style="max-width: 800px; height: 30px;">
                <img src="{{notification.post.image.url}}" class="mx-4" width="50px" height="50px">
                <h3 class="pt-1">{{notification.action_user.username}} liked your post </h3>   
            </div>
        </a>
      </div>


        {% else %}
        <div class="infinite-item">
            <a href = "{% url 'posts:post_detail' notification.post.id %}">
                <div class="row" style="max-width: 800px; height: 30px;">
                    <img src="{{notification.post.image.url}}" class="mx-4" width="50px" height="50px">
                    <h3 class="pt-1">{{notification.action_user.username}} commented on your post </h3>   
                </div>    
            </a>
        </div>
       
        {% endif %}

    {% endfor %}
</div>


{% if old_notifs.has_next %}
<div class="loading">
  <h4><a class="infinite-more-link" href="?page={{old_notifs.next_page_number}}">More</a></h4>
</div>
{% endif %}



{% endblock %}